# Generated by Django 4.0.1 on 2022-01-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tins',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tin', models.CharField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sell_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_exists', models.BooleanField(default=False)),
                ('start_ts', models.DateTimeField(blank=True, null=True)),
                ('parsing_ts', models.DateTimeField(blank=True, null=True)),
                ('tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tins')),
            ],
        ),
    ]
